search_field = "class:search__input"
search_button = "css:.search__btn-search"
product_click = "class:productname"
basket_button = "class:addtobasket-container"
komunikat = "class:modal-body"
blad = "class:alert-info"